"""add timestamp

Revision ID: 6710b1840754
Revises: e952cd4cbbb4
Create Date: 2020-05-31 10:19:20.082961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6710b1840754'
down_revision = 'e952cd4cbbb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookbooks', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_cookbooks_timestamp'), 'cookbooks', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cookbooks_timestamp'), table_name='cookbooks')
    op.drop_column('cookbooks', 'timestamp')
    # ### end Alembic commands ###
