"""add likes

Revision ID: 9576afee59ac
Revises: 6710b1840754
Create Date: 2020-06-01 15:00:36.023247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9576afee59ac'
down_revision = '6710b1840754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookbooks', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookbooks', 'likes')
    # ### end Alembic commands ###
