"""fix bug

Revision ID: e952cd4cbbb4
Revises: f8ab6758fe2b
Create Date: 2020-05-30 21:24:45.332495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e952cd4cbbb4'
down_revision = 'f8ab6758fe2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookbooks', sa.Column('myfoods', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookbooks', 'myfoods')
    # ### end Alembic commands ###
